"""
Hermes plugin discovery path installation.

Lifecycle:
1. ``install_plugin`` — symlink or wrapper-mode plugin in the default home,
   plus per-profile links for every opted-in Hermes profile.
2. ``uninstall_plugin`` — remove the plugin link and all per-profile links.
3. ``install_status`` — ``mnemosyne-hermes status`` checks both the default
   home and every opted-in profile.
"""
from __future__ import annotations

import os
import re
import shutil
import site
import subprocess
import sys
from pathlib import Path
from typing import Optional

PLUGIN_NAME = "mnemosyne"


def hermes_home() -> Path:
    """Return the effective Hermes home directory."""
    home = os.environ.get("HERMES_HOME", "").strip()
    if home:
        return Path(home).expanduser().resolve()
    return Path.home() / ".hermes"


def plugin_target_dir(hermes_home_path: str | Path | None = None) -> Path:
    """Return the path where the Mnemosyne plugin should be installed."""
    base = Path(hermes_home_path).expanduser() if hermes_home_path else hermes_home()
    return base / "plugins" / PLUGIN_NAME


def _resolve_package_dir() -> Path:
    """Return the directory containing this package (the mnemosyne_hermes source)."""
    # __file__ is .../mnemosyne_hermes/install.py -> parent is the package dir
    return Path(__file__).parent.resolve()


def _site_packages_for_python(python: Path) -> Path:
    """Get the site-packages path from a specific Python interpreter."""
    result = subprocess.run(
        [str(python), "-c", "import site; print(site.getsitepackages()[0])"],
        capture_output=True,
        text=True,
        check=True,
    )
    return Path(result.stdout.strip())


def _check_wrapper_import(site_packages: Path, python: Path) -> tuple[bool, str]:
    """Check that mnemosyne_hermes is importable from the given Python environment."""
    result = subprocess.run(
        [
            str(python), "-c",
            f"import sys; sys.path.insert(0, {str(site_packages)!r}); ",
            "from mnemosyne_hermes import __version__; print(__version__)",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        return True, result.stdout.strip()
    return False, result.stderr.strip()


def _copy_plugin_yaml(target: Path) -> None:
    """Copy plugin.yaml alongside the wrapper plugin."""
    plugin_yaml = _resolve_package_dir() / "plugin.yaml"
    if plugin_yaml.is_file():
        import shutil
        shutil.copy2(plugin_yaml, target / "plugin.yaml")


def _prepare_plugin_target(base: Path, target: Path, *, force: bool = False) -> None:
    """Ensure the plugin target directory is ready for installation.

    Creates parent directories and handles existing symlinks/directories.
    """
    if not target.is_symlink() and not target.exists():
        target.parent.mkdir(parents=True, exist_ok=True)
        return

    if not force:
        raise FileExistsError(
            f"Plugin target {target} already exists. Use --force to replace."
        )

    if target.is_symlink():
        target.unlink()
    elif target.is_dir():
        shutil.rmtree(target)
    else:
        target.unlink()

    target.parent.mkdir(parents=True, exist_ok=True)


def _write_wrapper_plugin(target: Path, *, python: Path, site_packages: Path) -> None:
    """Create a persistent Hermes plugin shim that imports from a selected env."""
    target.mkdir(parents=True, exist_ok=False)
    init_source = f"""\"\"\"Persistent Mnemosyne Hermes plugin wrapper.

Generated by ``mnemosyne-hermes install --mode wrapper``. The wrapper keeps the
Hermes discovery directory stable while importing the real ``mnemosyne_hermes``
package from the selected Python environment.
\"\"\"
from __future__ import annotations

import sys as _sys

# Metadata used by ``mnemosyne-hermes status``.
_PYTHON = {str(python)!r}
_SITE = {str(site_packages)!r}

if _SITE not in _sys.path:
    _sys.path.insert(0, _SITE)

# Hermes discovery marker: register_memory_provider / MnemosyneMemoryProvider
from mnemosyne_hermes import *  # noqa: F401,F403,E402
"""
    (target / "__init__.py").write_text(init_source, encoding="utf-8")
    _copy_plugin_yaml(target)


def install_plugin(
    *,
    hermes_home_path: str | Path | None = None,
    force: bool = False,
    mode: str = "symlink",
    python: str | Path | None = None,
) -> Path:
    """Install the Mnemosyne provider into Hermes' user plugin directory.

    ``mode='symlink'`` keeps the historical behavior. ``mode='wrapper'``
    creates a real persistent plugin directory containing a tiny shim that adds
    the selected interpreter's site-packages path to ``sys.path`` and imports
    ``mnemosyne_hermes`` from there.

    After installing the primary plugin, every opted-in profile under
    ``<hermes_home>/profiles/*`` that selects ``memory.provider: mnemosyne``
    also gets a per-profile symlink.
    """
    if mode not in {"symlink", "wrapper"}:
        raise ValueError("mode must be 'symlink' or 'wrapper'")

    source = _resolve_package_dir()
    if not source.is_dir():
        raise FileNotFoundError(f"mnemosyne_hermes package not found at {source}")

    base = Path(hermes_home_path).expanduser() if hermes_home_path else hermes_home()
    target = plugin_target_dir(hermes_home_path)
    _prepare_plugin_target(base, target, force=force)

    if mode == "symlink":
        os.symlink(str(source), str(target))
    else:
        wrapper_python = Path(python).expanduser() if python else Path(sys.executable)
        if not wrapper_python.is_file():
            raise FileNotFoundError(f"Python interpreter not found: {wrapper_python}")
        site_packages = _site_packages_for_python(wrapper_python)
        import_ok, import_error = _check_wrapper_import(site_packages, wrapper_python)
        if not import_ok:
            raise RuntimeError(
                "Selected Python environment cannot import mnemosyne_hermes: "
                f"{import_error}"
            )
        _write_wrapper_plugin(target, python=wrapper_python, site_packages=site_packages)

    # Link any named profiles that opt into Mnemosyne (no-op without profiles).
    _link_all_profiles(source, hermes_home_path=hermes_home_path, force=force)

    return target


def _config_selects_mnemosyne(text: str) -> bool:
    """Return True when a profile config selects ``memory.provider: mnemosyne``.

    Prefers a real YAML parse, which ignores comments and tolerates arbitrary
    whitespace. The line-anchored regex is used **only** when PyYAML is genuinely
    unavailable (``ImportError``). Malformed YAML is treated as "not opted in"
    rather than falling through to the looser regex.
    """
    try:
        import yaml
    except ImportError:
        return re.search(
            r"^\s*provider\s*:\s*mnemosyne\s*(#.*)?$", text, re.MULTILINE
        ) is not None
    try:
        cfg = yaml.safe_load(text)
    except yaml.YAMLError:
        return False
    if isinstance(cfg, dict):
        memory = cfg.get("memory")
        if isinstance(memory, dict):
            return memory.get("provider") == "mnemosyne"
    return False


def _iter_mnemosyne_profiles(hermes_home_path: str | Path | None = None) -> list[Path]:
    """Return profile dirs under <hermes_home>/profiles/* that opt into Mnemosyne.

    A profile opts in when its ``config.yaml`` parses to
    ``memory.provider == "mnemosyne"`` (see ``_config_selects_mnemosyne``).
    Symlinked profile entries are skipped (the installer must not follow a
    profile symlink and write under its target). Profiles without a
    ``config.yaml`` are skipped. Returns an empty list when no ``profiles/``
    directory exists (the default, no-profile install).
    """
    base = Path(hermes_home_path).expanduser() if hermes_home_path else hermes_home()
    profiles_dir = base / "profiles"
    if not profiles_dir.is_dir():
        return []
    selected: list[Path] = []
    for child in sorted(profiles_dir.iterdir()):
        if child.is_symlink():
            continue
        if not child.is_dir():
            continue
        config_path = child / "config.yaml"
        if not config_path.is_file():
            continue
        try:
            text = config_path.read_text(encoding="utf-8")
        except OSError:
            continue
        if _config_selects_mnemosyne(text):
            selected.append(child)
    return selected


def _link_profile(profile_home: Path, source: Path, *, force: bool = False) -> Optional[Path]:
    """Symlink ``profile_home/plugins/mnemosyne`` to source. Idempotent.

    A link already pointing at ``source`` is left untouched. A stale or broken
    link is replaced only when ``force`` is set; otherwise it is left in place
    and reported. Returns the link path on success, else None.
    """
    target = profile_home / "plugins" / PLUGIN_NAME
    target.parent.mkdir(parents=True, exist_ok=True)

    if target.is_symlink() or target.exists():
        try:
            already = target.resolve() == source.resolve()
        except OSError:
            already = False
        if already:
            print(f"  Profile {profile_home.name}: already linked")
            return target
        if not force:
            print(f"  Profile {profile_home.name}: exists, skipped (use --force to replace)")
            return None
        if target.is_symlink():
            print(f"  Profile {profile_home.name}: replacing existing link -> {target.readlink()}")
            target.unlink()
        elif target.is_dir():
            print(f"  Profile {profile_home.name}: replacing existing directory {target}")
            shutil.rmtree(target)
        else:
            print(f"  Profile {profile_home.name}: replacing existing file {target}")
            target.unlink()

    try:
        os.symlink(str(source), str(target))
    except OSError as e:
        print(f"  Profile {profile_home.name}: failed to link: {e}")
        return None
    print(f"  Profile {profile_home.name}: linked {target}")
    return target


def _link_all_profiles(
    source: Path,
    *,
    hermes_home_path: str | Path | None = None,
    force: bool = False,
) -> list[Path]:
    """Link Mnemosyne into every opted-in profile. No-op without profiles.

    A failure on one profile is reported and does not abort the remaining
    profiles.
    """
    linked: list[Path] = []
    for profile_home in _iter_mnemosyne_profiles(hermes_home_path):
        try:
            result = _link_profile(profile_home, source, force=force)
        except OSError as e:
            print(f"  Profile {profile_home.name}: failed: {e}")
            continue
        if result is not None:
            linked.append(result)
    return linked


def _verify_links(*, hermes_home_path: str | Path | None = None) -> bool:
    """Print PASS/FAIL for each home that should have a resolvable plugin link.

    Checks the default home plus every opted-in profile. Returns True only
    when every checked link resolves to the provider source.
    """
    source = _resolve_package_dir()
    base = Path(hermes_home_path).expanduser() if hermes_home_path else hermes_home()
    homes: list[Path] = [base]
    homes.extend(_iter_mnemosyne_profiles(hermes_home_path))

    all_ok = True
    print("Verifying plugin links...")
    for home in homes:
        target = home / "plugins" / PLUGIN_NAME
        ok = target.is_symlink() or target.exists()
        if ok:
            try:
                ok = target.resolve() == source.resolve()
            except OSError:
                ok = False
        all_ok = all_ok and ok
        print(f"  {'PASS' if ok else 'FAIL'}  {home.name or home}: {target}")
    return all_ok


def _unlink_all_profiles(*, hermes_home_path: str | Path | None = None) -> None:
    """Remove the per-profile plugin links created by ``_link_all_profiles``.

    Scans every profile directory by *link*, not by config opt-in: a profile's
    ``plugins/mnemosyne`` is removed when it is a symlink resolving to the
    provider source, regardless of what (or whether) the profile's
    ``config.yaml`` currently selects. This still never touches a real directory
    or a link pointing elsewhere. Symlinked profile entries are skipped.
    """
    base = Path(hermes_home_path).expanduser() if hermes_home_path else hermes_home()
    profiles_dir = base / "profiles"
    if not profiles_dir.is_dir():
        return
    source = _resolve_package_dir()
    for child in sorted(profiles_dir.iterdir()):
        if child.is_symlink():
            continue
        target = child / "plugins" / PLUGIN_NAME
        if not target.is_symlink():
            continue
        try:
            if target.resolve() == source.resolve():
                target.unlink()
                print(f"  Removed profile link: {target}")
        except OSError:
            continue
